Fox Jinja2 build error
The error was:

```
  File "/Users/mb312/.virtualenvs/test/lib/python3.9/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/mb312/.virtualenvs/test/lib/python3.9/site-packages/jinja2/__init__.py)
```

The cause was the removal of `environmentfilter` from the Jinja2,
apparently in Jinja2 3.1.

See: https://github.com/sphinx-doc/sphinx/issues/10291 for discussion.